name: aho_corasick
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/MaximilianKlein/aho_corasick
author: Maximilian Klein <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
